### ISSUE TITLE
macOS 10.12.4 broke the youtube killer or plugin.

### ISSUE THREAD

**Issue by vmachiel** [hoyois/plugin-to-html5#28]
Pretty much the title. I've tried both the regular and the alternative youtube killer scripts, no luck. I pretty much see this: 
<img width="871" alt="schermafbeelding 2017-03-28 om 13 13 03" src="https://cloud.githubusercontent.com/assets/7748935/24402328/516af800-13b8-11e7-85a8-220a644e47ee.png">

Anyone else experience this? Anything I can do about it? Thanks!

**Comment by hiuwo** [comment]
Not sure if this helps at all since I'm not fixing your killer. but YouTube has html5 full support now. If you just remove the old YouTube killer is from the list, you can actually use the better built-in html5.

**Comment by vmachiel** [comment]
Yeah I know, but I hate the youtube player with a passion. The one the this plugin provides is so much clear and buffer the whole video making skipping around much easier.

**Comment by londor** [comment]
Same problem here. Black screen when trying to play the content, download button still works though. Hopefully Marc can take a look at it and fix it soonish. And it was Safari 10.1 that broke the plugin as I'm still on macOS 10.11.6.

**Comment by hoyois** [comment]
The culprit is the latest Safari update which does not recognize CSS selectors with multiple pseudo-elements. This seems like a bug to me, so there is a chance this will fix itself in a future Safari update. Unfortunately this has nothing to do with the YouTube killer and it cannot be easily fixed without recompiling the extension, which I can't do.

**Comment by hoyois** [comment]
Actually this short script fixes the problem:

https://raw.githubusercontent.com/hoyois/plugin-to-html5/master/CSSfix.js

**Comment by londor** [comment]
Great. Thank you so much!

**Comment by vmachiel** [comment]
That's amazing hoyois, thanks so much!
